version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  django:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - RUN_MIGRATIONS=true

  celery:
    build: .
    command: celery -A xiangqi_lite worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0-alpine
    ports:
      - "6380:6379"
