# Generated by Django 5.1 on 2024-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
