# Generated by Django 5.1.1 on 2024-09-11 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['red_player'], name='game_game_red_pla_889b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player'], name='game_game_black_p_df3708_idx'),
        ),
    ]
