# Generated by Django 5.1 on 2024-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='game',
            name='black_time_remaining',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='game',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='red_time_remaining',
            field=models.IntegerField(default=600),
        ),
    ]
